name: Build GitHub Container Registry

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'R/**'
      - 'app.R'
      - 'www/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Make prepare-deploy.sh executable
        run: chmod +x prepare-deploy.sh

      - name: Prepare deployment folder
        run: ./prepare-deploy.sh

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./deploy
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/causalityapp:latest
